theme: jekyll-theme-minimal
title: Chroma Unleashed Magic
description: Custom magic set with over 280 new cards


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
